-- 删除现有表
DROP TABLE IF EXISTS OrderFood;
DROP TABLE IF EXISTS UserFavoriteMerchant;
DROP TABLE IF EXISTS UserFavoriteDish;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS CommentMerchant;
DROP TABLE IF EXISTS CommentFood;
DROP TABLE IF EXISTS ScoreMerchant;
DROP TABLE IF EXISTS ScoreFood;
DROP TABLE IF EXISTS UserOrder;
DROP TABLE IF EXISTS Food;
DROP TABLE IF EXISTS FoodClassification;
DROP TABLE IF EXISTS Merchant;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Admins;


-- 创建 Admins 表
CREATE TABLE Admins (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL COMMENT '帐号',
    pwd VARCHAR(50) NOT NULL COMMENT '密码',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 User 表
CREATE TABLE User (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    student_number VARCHAR(50) NOT NULL COMMENT '学号/工号',
    pwd VARCHAR(50) NOT NULL COMMENT '密码',
    name VARCHAR(50) NOT NULL COMMENT '姓名',
    sex VARCHAR(255) NOT NULL COMMENT '性别',
    BirthDate DATE NOT NULL COMMENT '年龄',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 Merchant 表
CREATE TABLE Merchant (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    account VARCHAR(50) NOT NULL COMMENT '账号',
    pwd VARCHAR(50) NOT NULL COMMENT '密码',
    name VARCHAR(255) NOT NULL COMMENT '店家名称',
    address VARCHAR(50) NOT NULL COMMENT '地址',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 FoodClassification 表
CREATE TABLE FoodClassification (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL COMMENT '分类名称',
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 Food 表
CREATE TABLE Food (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL COMMENT '菜品名称',
    classificationId INT(10) UNSIGNED NOT NULL COMMENT '分类编号',
    picture VARCHAR(255) NOT NULL COMMENT '菜品图片',
    score DECIMAL(18,2) NOT NULL COMMENT '评分',
    price DECIMAL(18,2) NOT NULL COMMENT '价格',
    sales_volume INT(11) NOT NULL COMMENT '销量',
    description LONGTEXT NOT NULL COMMENT '菜品描述',
    nutrition LONGTEXT NOT NULL COMMENT '菜品营养',
    ingredient LONGTEXT NOT NULL COMMENT '菜品成分',
    allergy LONGTEXT NOT NULL COMMENT '菜品过敏源',
    MerchantId INT(10) UNSIGNED NOT NULL COMMENT '发布商户编号',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否被删除',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (classificationId) REFERENCES FoodClassification(id)ON DELETE CASCADE,
    FOREIGN KEY (MerchantId) REFERENCES Merchant(id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 UserOrder 表（整合了 OrderFood 表）
CREATE TABLE UserOrder (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    foodId INT(10) UNSIGNED NOT NULL COMMENT '菜品id',
    detail TEXT NOT NULL COMMENT '订单信息',
    price_amount DECIMAL(18,2) NOT NULL COMMENT '订单金额',
    userId INT(10) UNSIGNED NOT NULL COMMENT '下单人',
    merchantId INT(10) UNSIGNED NOT NULL COMMENT '下单商户',
    status VARCHAR(50) NOT NULL COMMENT '状态',
    is_paid VARCHAR(10) NOT NULL DEFAULT '否' COMMENT '是否支付',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES User(id)ON DELETE CASCADE,
    FOREIGN KEY (foodId) REFERENCES Food(id)ON DELETE CASCADE,
    FOREIGN KEY (merchantId) REFERENCES Merchant(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 UserFavoriteMerchant 表
CREATE TABLE UserFavoriteMerchant (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    merchantId INT(10) UNSIGNED NOT NULL COMMENT '商户id',
    userId INT(10) UNSIGNED NOT NULL COMMENT '收藏人id',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (merchantId) REFERENCES Merchant(id)ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 UserFavoriteDish 表
CREATE TABLE UserFavoriteDish (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    foodId INT(10) UNSIGNED NOT NULL COMMENT '菜品id',
    userId INT(10) UNSIGNED NOT NULL COMMENT '收藏人id',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (foodId) REFERENCES Food(id)ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 Message 表
CREATE TABLE Message (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    orderId INT(10) UNSIGNED NOT NULL COMMENT '订单ID',
    content TEXT NOT NULL COMMENT '消息信息',
    userId INT(10) UNSIGNED NOT NULL COMMENT '下单人',
    status VARCHAR(50) NOT NULL COMMENT '状态',
    merchantId INT(10) UNSIGNED NOT NULL COMMENT '店家',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES UserOrder(id)ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id)ON DELETE CASCADE,
    FOREIGN KEY (merchantId) REFERENCES Merchant(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 CommentMerchant 表
CREATE TABLE CommentMerchant (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    merchantId INT(10) UNSIGNED NOT NULL COMMENT '商户id',
    content TEXT NOT NULL COMMENT '评论内容',
    commenterId INT(10) UNSIGNED NOT NULL COMMENT '评论人id',
    orderId INT(10) UNSIGNED NOT NULL COMMENT '订单id',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES UserOrder(id)ON DELETE CASCADE,
    FOREIGN KEY (merchantId) REFERENCES Merchant(id)ON DELETE CASCADE,
    FOREIGN KEY (commenterId) REFERENCES User(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 CommentFood 表
CREATE TABLE CommentFood (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    foodId INT(10) UNSIGNED NOT NULL COMMENT '菜品id',
    content TEXT NOT NULL COMMENT '评论内容',
    commenterId INT(10) UNSIGNED NOT NULL COMMENT '评论人id',
    orderId INT(10) UNSIGNED NOT NULL COMMENT '订单id',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES UserOrder(id)ON DELETE CASCADE,
    FOREIGN KEY (foodId) REFERENCES Food(id)ON DELETE CASCADE,
    FOREIGN KEY (commenterId) REFERENCES User(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 ScoreMerchant 表
CREATE TABLE ScoreMerchant (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    merchantId INT(10) UNSIGNED NOT NULL COMMENT '商户id',
    score DECIMAL(18,2) NOT NULL COMMENT '评分',
    commenterId INT(10) UNSIGNED NOT NULL COMMENT '评论人id',
    orderId INT(10) UNSIGNED NOT NULL COMMENT '订单id',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES UserOrder(id)ON DELETE CASCADE,
    FOREIGN KEY (merchantId) REFERENCES Merchant(id)ON DELETE CASCADE,
    FOREIGN KEY (commenterId) REFERENCES User(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 创建 ScoreFood 表
CREATE TABLE ScoreFood (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    foodId INT(10) UNSIGNED NOT NULL COMMENT '菜品id',
    score DECIMAL(18,2) NOT NULL COMMENT '评分',
    commenterId INT(10) UNSIGNED NOT NULL COMMENT '评论人id',
    orderId INT(10) UNSIGNED NOT NULL COMMENT '订单id',
    add_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
    PRIMARY KEY (id),
    FOREIGN KEY (orderId) REFERENCES UserOrder(id)ON DELETE CASCADE,
    FOREIGN KEY (foodId) REFERENCES Food(id)ON DELETE CASCADE,
    FOREIGN KEY (commenterId) REFERENCES User(id)ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
